export default [
    {
        label: "委外计划单号",
        prop: "planNumber",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "生产订单号",
        prop: "icmoNumber",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "工序代码",
        prop: "processNumber",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "工序名称",
        prop: "processName",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "产品代码",
        prop: "productNumber",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "产品名称",
        prop: "productName",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "计划数量",
        prop: "planOutQty",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "发出总数",
        prop: "actualOutQty",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      
      {
        label: "单价",
        prop: "price",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "金额",
        prop: "amount",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      
      {
        label: "供应商代码",
        prop: "supplyNumber",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "供应商名称",
        prop: "supplyName",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "申请部门代码",
        prop: "deptNumber",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "申请部门名称",
        prop: "deptName",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "状态",
        prop: "status",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },

]