import authority from "../authority";
//属性对照element ui的组件
export default {
  componentComparison: {
    falseString: {
      classKey: "",
      label: "",
      tag: "el-input",
      placeholder: "请输入",
      clearable: true,
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    trueString: {
      classKey: "",
      label: "",
      tag: "id-select",
      options: [],
      placeholder: "请输入",
      multiple: true,
      filterable: true,
      allowCreate: true,
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    falseNumber: {
      classKey: "",
      label: "",
      tag: "el-input-number",
      placeholder: "请输入",
      controlsPosition: "right",
      min: 0,
      max: 100000,
      step: 0.01,
      // precision:3,//精度
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    trueNumber: {
      classKey: "",
      label: "",
      tag: "id-select",
      options: [],
      placeholder: "请输入",
      multiple: true,
      filterable: true,
      allowCreate: true,
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    falseCheckbox: {
      classKey: "",
      label: "",
      tag: "el-checkbox",
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    trueCheckbox: {
      classKey: "",
      label: "",
      tag: "id-checkbox-group",
      options: [
        {
          label: "是",
          authority: new authority(),
        },
        {
          label: "否",
          authority: new authority(),
        },
      ],
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    falseDatetime: {
      classKey: "",
      label: "",
      tag: "el-date-picker",
      type: "datetimerange",
      gridRowStart: 1,
      gridColumnStart: 1,
      rangeSeparator: "-",
      startPlaceholder: "开始时间",
      endPlaceholder: "结束时间",
      placeholder: "选择时间范围",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    trueDatetime: {
      classKey: "",
      label: "",
      tag: "el-date-picker",
      type: "datetimerange",
      gridRowStart: 1,
      gridColumnStart: 1,
      rangeSeparator: "-",
      startPlaceholder: "开始时间",
      endPlaceholder: "结束时间",
      placeholder: "选择时间范围",
      valueFormat: "yyyy-MM-dd HH:mm:ss",
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    falseSelectExpand: {
      classKey: "",
      label: "",
      tag: "id-select-expand",
      placeholder: "按名称搜索",
      selectItems: "",
      defaultFirstOption: true,
      clearable: true,
      event: {
        // querySelectItems:function (val) {
        //   return val;
        // },
      },
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    trueSelectExpand: {
      classKey: "",
      label: "",
      tag: "id-select-expand",
      placeholder: "按名称搜索",
      multiple: true,
      selectItems: [],
      defaultFirstOption: true,
      clearable: true,
      event: {
        // querySelectItems:function (val) {
        //   return val;
        // },
      },
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    falseSelect: {
      classKey: "",
      label: "",
      tag: "id-select",
      placeholder: "请选择",
      clearable: true,
      options: [],
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    trueSelect: {
      classKey: "",
      label: "",
      tag: "id-select",
      placeholder: "请选择",
      multiple: true,
      clearable: true,
      options: [],
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
  },
};
