import { AppMenuType } from "@/interfaces/enum";

export default [
  {
    key: "worker_order",
    title: "新e工单",
    icon: "",
    type: AppMenuType.CUSTOM,
    children: [
      {
        key: "/workerorder/prdplan",
        title: "生产计划",
        icon: "",
        type: AppMenuType.CUSTOM,
        children: [
          {
            key: "/workerorder/prdorder/list",
            title: "生产订单-高朋",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "生产订单",
            path: "/workerorder/prdorder/list",
          },
        ],
      },
      {
        key: "productionaction",
        title: "生产执行",
        icon: "",
        type: AppMenuType.CUSTOM,
        children: [
          {
            key: "/productionaction/prdprocess",
            title: "工序任务-吴宇璠",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "工序任务",
            path: "/productionaction/prdprocess",
          },
          // {
          //   key: "",
          //   title: "派工单",
          //   icon: "",
          //   type: AppMenuType.CUSTOM,
          //   pathName: "派工单",
          //   path: "",
          // },
          {
            key: "/productionaction/prdstart",
            title: "开工记录-吴宇璠",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "开工记录",
            path: "/productionaction/prdstart",
          },
          {
            key: "/productionaction/reportrecord",
            title: "汇报记录-吴宇璠",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "汇报记录",
            path: "/productionaction/reportrecord",
          },
        ],
      },
      // {
      //   key: "/workerorder/prddone",
      //   title: "生产执行-高朋",
      //   icon: "",
      //   type: AppMenuType.CUSTOM,
      //   pathName: "生产执行",
      //   path: "/workerorder/prddone",
      // }
    ],
  },
  {
    key: "out_plan",
    title: "新委外计划",
    icon: "",
    type: AppMenuType.CUSTOM,
    children: [
      {
        key: "/out/plan/list",
        title: "委外计划",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "委外计划",
        path: "/out/plan/list",
      },
      {
        key: "/out/sendout",
        title: "委外发出",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "委外发出",
        path: "/out/sendout",
      },
      {
        key: "/out/receive",
        title: "委外接收-宇璠",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "委外接收",
        path: "/out/receive",
      },
      {
        key: "/out/check/list",
        title: "委外检验",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "委外检验",
        path: "/out/check/list",
      },
    ],
  },
  {
    key: "adjust",
    title: "数量调整",
    icon: "",
    type: AppMenuType.CUSTOM,
    children: [
      {
        key: "/quantityadjust/adjustquantity",
        title: "数量调整",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "数量调整",
        path: "/quantityadjust/adjustquantity",
      },
      {
        key: "/quantityadjust/adjustrecord",
        title: "调整记录",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "调整记录",
        path: "/quantityadjust/adjustrecord",
      },
    ],
  },

  {
    key: "productioncheck",
    title: "生产检验",
    icon: "",
    type: AppMenuType.CUSTOM,
    children: [
      {
        key: "/productioncheck/list",
        title: "生产检验",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "生产检验",
        path: "/productioncheck/list",
      },
    ],
  },

  // 工厂建模
  {
    key: "factoryModel",
    title: "新工厂建模",
    icon: "",
    type: AppMenuType.CUSTOM,
    children: [
      {
        key: "basicData",
        title: "基础资料",
        icon: "",
        type: AppMenuType.CUSTOM,
        children: [
          {
            key: "/factoryModel/material/list",
            title: "物料",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "物料",
            path: "/factorymodel/material/list",
          },

          {
            key: "/factorymodel/productprocess/list",
            title: "产品工艺",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "产品工艺",
            path: "/factorymodel/productprocess/list",
          },
          {
            key: "222",
            title: "产品工序",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "产品工序",
            path: "",
          },
          {
            key: "/factorymodel/device/list",
            title: "设备",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "设备",
            path: "/factorymodel/device/list",
          },
          {
            key: "/factorymodel/group/list",
            title: "班组",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "班组",
            path: "/factorymodel/group/list",
          },
          {
            key: "/factorymodel/class/list",
            title: "班次",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "班次",
            path: "/factorymodel/class/list",
          },

          {
            key: "/factorymodel/basicData/department/index",
            title: "部门",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "部门",
            path: "/factorymodel/basicData/department/index",
          },

          {
            key: "/factorymodel/employee/list",
            title: "人员",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "人员",
            path: "/factorymodel/employee/list",
          },
          {
            key: "/factorymodel/customer/list",
            title: "客户",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "客户",
            path: "/factorymodel/customer/list",
          },
          {
            key: "/factorymodel/supplier/list",
            title: "供应商",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "供应商",
            path: "/factorymodel/supplier/list",
          },
          {
            key: "/factorymodel/basicData/unitMeasure/index",
            title: "计量单位",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "计量单位",
            path: "/factorymodel/basicData/unitMeasure/index",
          },
          {
            key: "/factorymodel/basicData/badReason/index",
            title: "不良原因",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "不良原因",
            path: "/factorymodel/basicData/badReason/index",
          },
          {
            key: "/windowSelect/index",
            title: "弹窗",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "弹窗",
            path: "/windowSelect/index",
          },
        ],
      },
      {
        key: "8888",
        title: "配置资料",
        icon: "",
        type: AppMenuType.CUSTOM,
        children: [
          {
            key: "/factoryModel/factory/index",
            title: "工厂建模",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "工厂建模",
            path: "/factoryModel/factory/index",
          },
          {
            key: "/factorymodel/materialCategory/list",
            title: "物料类别",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "物料类别",
            path: "/factorymodel/materialCategory/list",
          },

          {
            key: "/factorymodel/devicecategory/list",
            title: "设备类别",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "设备类别",
            path: "/factorymodel/devicecategory/list",
          },
          {
            key: "/factorymodel/salary/list",
            title: "工资配置",
            icon: "",
            type: AppMenuType.CUSTOM,
            pathName: "工资配置",
            path: "/factorymodel/salary/list",
          },
        ],
      },
    ],
  },
  {
    key: "demo",
    title: "标准示例",
    icon: "",
    type: AppMenuType.CUSTOM,
    children: [
      {
        key: "/demo/list",
        title: "示例-列表",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "示例-列表",
        path: "/demo/list",
      },
      // {
      //   key: "/demo/edit",
      //   title: "示例-编辑",
      //   icon: "",
      //   type: AppMenuType.CUSTOM,
      //   pathName: "示例-编辑",
      //   path: "/demo/edit",
      // },
      {
        key: "/demo/tree",
        title: "示例-树形视图",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "示例-树形视图",
        path: "/demo/tree",
      },
      {
        key: "/demo/treeTwo",
        title: "示例-树类型及右表",
        icon: "",
        type: AppMenuType.CUSTOM,
        pathName: "示例-树类型及右表",
        path: "/demo/treeTwo",
      },
    ],
  },
];
