import auditTableColumns from './auditTableColumns';
import disableTableColumns from './disableTableColumns';

const clerkInputPopupColumns=[
  {
    tag: "el-table-column",
    label: "员工代码",
    prop: "number",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "员工名称",
    prop: "name",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "员工属性",
    prop: "type",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "Select",
    options: [
      {
        label: "在职",
        value: "0",
        authority: {
          idLoad: false,
          idIf: true,
          idDisable: false,
          idShow: true,
        },
      },
      {
        label: "试用",
        value: "1",
        authority: {
          idLoad: false,
          idIf: true,
          idDisable: false,
          idShow: true,
        },
      },
      {
        label: "实习",
        value: "2",
        authority: {
          idLoad: false,
          idIf: true,
          idDisable: false,
          idShow: true,
        },
      },
      {
        label: "退休",
        value: "3",
        authority: {
          idLoad: false,
          idIf: true,
          idDisable: false,
          idShow: true,
        },
      },
      {
        label: "离职",
        value: "4",
        authority: {
          idLoad: false,
          idIf: true,
          idDisable: false,
          idShow: true,
        },
      },
      {
        label: "离休",
        value: "5",
        authority: {
          idLoad: false,
          idIf: true,
          idDisable: false,
          idShow: true,
        },
      },
    ],
  },
  {
    tag: "el-table-column",
    label: "所属部门代码",
    prop: "departmentNumber",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "所属部门名称",
    prop: "departmentName",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "所属班组代码",
    prop: "teamNumber",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "所属班组名称",
    prop: "teamName",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "邮箱",
    prop: "email",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "家庭地址",
    prop: "address",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "联系电话",
    prop: "phone",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "备注",
    prop: "note",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "制单人代码",
    prop: "docMakerNumber",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "制单人姓名",
    prop: "docMakerName",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    tag: "el-table-column",
    label: "创建时间",
    prop: "createTime",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "Datetime",
  },
  {
    tag: "el-table-column",
    label: "更新时间",
    prop: "updateTime",
    minWidth: 180,
    showOverflowTooltip: true,
    resizable: false,
    comp: "Datetime",
  },
];
const clerkTableColumns=[clerkInputPopupColumns,auditTableColumns,disableTableColumns].flat(1);
export {clerkTableColumns as default,clerkInputPopupColumns};
