export const groupModel={
  data: {
    id: '',
    pid:'',
    type:'',
    number: '',
    name: '',
    note: '',
    orgId: 0,
  },
  rules: {
    number: [{ required: true, message: "分组代码不能为空", trigger: "blur" }],
    name: [{ required: true, message: "分组名称不能为空", trigger: "blur" }],
  },
  component: [
    {
      classKey: "number",
      label: "分组代码",
      tag: "el-input",
      placeholder: "请输入",
      clearable: true,
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    {
      classKey: "name",
      label: "分组名称",
      tag: "el-input",
      placeholder: "请输入",
      clearable: true,
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
    {
      classKey: "note",
      label: "备注",
      tag: "el-input",
      placeholder: "请输入",
      type: "textarea",
      rows: 3, //需要人员自己调整
      gridRowStart: 2,
      gridColumnStart: 1,
      maxlength: 250,
      showWordLimit: true,
      idLoad: false,
      idIf: true,
      idDisable: false,
      idShow: true,
    },
  ],
};
