export default [
    {
        label: "委外发出单号",
        prop: "billNo",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "生产订单",
        prop: "icomNbr",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "工序编码",
        prop: "processCode",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "工序名称",
        prop: "processName",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "委外计划数量",
        prop: "planOutQty",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "委外发出数量",
        prop: "outQty",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "已接收数量合格数量",
        prop: "sumRcvGoodQty",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "接收数量",
        prop: "rcvQty",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "发出时间",
        prop: "outTime",
        width: 250,
        comp: "String",
      },
]