export default [
  {
    label: "委外发出单号",
    prop: "billNo",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "委外计划单号",
    prop: "outPlanNo",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "供应商代码",
    prop: "supplierNumber",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "供应商名称",
    prop: "supplier",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "生产订单",
    prop: "icmoNbr",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "工序编码",
    prop: "processCode",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "工序名称",
    prop: "processName",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "委外计划数量",
    prop: "planOutQty",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "发出数量",
    prop: "outQty",
    minWidth: 180,
    showOverflowTooltip: true,
    comp: "String",
  },
  {
    label: "已接受合格数量",
    width: 180,
    prop: "sumRcvGoodQty",
    showOverflowTooltip: true,
    comp: "String",
  },
];
