export default [
    {
        label: "状态",
        prop: "billNo",
        minWidth: 180,
        showOverflowTooltip: true,
        comp: "String",
      },
    {
      label: "工序识别码",
      prop: "billNo",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
  {
      label: "工序名称",
      prop: "outPlanNo",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "产品代码",
      prop: "supplierNumber",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "产品名称",
      prop: "supplier",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "加工单元",
      prop: "icmoNbr",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "加工人员",
      prop: "processCode",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "汇报时间",
      prop: "processName",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "汇报数量",
      prop: "planOutQty",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "合格数量",
      prop: "outQty",
      minWidth: 180,
      showOverflowTooltip: true,
      comp: "String",
    },
    {
      label: "不合格数量",
      width:180,
      prop: "sumRcvGoodQty",
      showOverflowTooltip: true,
      comp: "String",
    },
    {
        label: "质检人",
        width:180,
        prop: "sumRcvGoodQty",
        showOverflowTooltip: true,
        comp: "String",
      },
      {
        label: "质检时间",
        width:180,
        prop: "sumRcvGoodQty",
        showOverflowTooltip: true,
        comp: "String",
      }
  ]